### PR TITLE
Connect sagas to the actual SUSE Manager config UI

### PR DESCRIPTION
**Pull request by dottorblaster**
# Description
Connecting the actual settings page to the settings API for SUSE Manager integration.

## How was this tested?
Jest tests updates, added new ones

### CODE REVIEW

**Review by nelsonkopliku — CHANGES_REQUESTED** [review]
Looking great!

Besides the two minor comments the main issues I found are:
- on saving when the certificate is left empty in the ui `ca_cert: ""` is passed to the api which does not pass validation. If the certificate is not wanted then the `ca_cert` property should not be in the api request payload.
- similarly, when patching settings if we want to remove the certificate, we need to provide the api with `ca_cert: null` instead of `ca_cert: ""` otherwise the same validation would not pass.

**Comment by dottorblaster** [comment]
@nelsonkopliku thanks for catching that behavior, I applied the fixes :+1:

**Review by nelsonkopliku — CHANGES_REQUESTED** [review]
Almost there.

Saving is working correctly, ca_cert is not sent if the user did not provide any :+1: 

On update, however, we need an explicit `ca_cert: null` if we want to remove the certificate, currently the field is not sent at all, meaning it remains untouched.

Besides this the Remove action seems to not be retained in the modal when changing creds like cert or password.

**Comment by dottorblaster** [comment]
@nelsonkopliku thanks! It should be okay now.

> Besides this the Remove action seems to not be retained in the modal when changing creds like cert or password.

I didn't quite understand this, but I guess you mean that closing and reopening the modal should display the `Remove` buttons again. I think I did something about that.

**Review by nelsonkopliku — APPROVED** [review]
Yes, you got it right! I was referring to that.

Besides the CI, LGTM. Great job!

**Comment by dottorblaster** [comment]
Thank you! :smile:

**Review by jamie-suse — APPROVED** [review]

**Pull request merged**
