### PR TITLE
Filter out unnecessary options

### PR DESCRIPTION
**Pull request by nelsonkopliku**
# Description

This PR makes sure that the relevant options are shown in Activity log's filter by activity type given the user's permission.
- activity types mapped to abilities
- activities filtered based on abilities

Currently the need is that users without user management abilities (`all:all` or `all:users`) do not see related options to filter by (`Login Attempt`, `User Created`, `User Modified`, `User Deleted`, `Profile Updated`).
Those activities won't ever be returned by the API anyways.

## How was this tested?

Automated tests.

### CODE REVIEW

**Comment by nelsonkopliku** [comment]
@abravosuse if you want to test this enhancement, here you have the PR environment https://2946.prenv.trento.suse.com/.

The expected behavior should be
- see user mgmt options in the filter
  - only `all:all` (aka superadmin) 
  - only `all:user`
  - `all:all` + some other abilities that is not `all:user`
  - `all:user` + some other abilities that is not `all:all`
- don't see user mgmt options in the filter
  - any abilities combination that does not contain `all:all` and `all:user`

**Comment by abravosuse** [comment]
> @abravosuse if you want to test this enhancement, here you have the PR environment https://2946.prenv.trento.suse.com/
> 
> The expected behavior should be
> 
> * see user mgmt options in the filter
>   
>   * only `all:all` (aka superadmin)
>   * only `all:users`
>   * `all:all` + some other abilities that is not `all:users`
>   * `all:users` + some other abilities that is not `all:all`
> * don't see user mgmt options in the filter
>   
>   * any abilities combination that does not contain `all:all` and `all:users`

I will test it @nelsonkopliku. Thank you. Just one question: can I update my rolling environment with this image or do I need to reinstall from scratch?

**Comment by nelsonkopliku** [comment]
@abravosuse I believe you could just update reference to this image `ghcr.io/trento-project/trento-web:2946-env`, if testing on the [PR env](https://2946.prenv.trento.suse.com/) is not enough.

**Comment by abravosuse** [comment]
> @abravosuse I believe you could just update reference to this image `ghcr.io/trento-project/trento-web:2946-env`, if testing on the [PR env](https://2946.prenv.trento.suse.com/) is not enough.

It should be enough @nelsonkopliku . What's the admin password again in the PR environment? Sorry I keep forgetting it...

**Review by abravosuse — APPROVED** [review]
Tested in PR environment. Works as expected! Good job!

**Review by gagandeepb — APPROVED** [review]
LGTM. Maybe at a later point, we can consider/evaluate if we want to push the activity types list from the backend, in a scoped (by user) manner.

**Review by balanza — APPROVED** [review]
LGTM

**Pull request merged**
