### PR TITLE
Split FE and BE tests in the CI

### PR DESCRIPTION
**Pull request by rtorrero**
# Description

This PR :
- splits the FE tests from the elixir tests. Since they don't depend on each other this might gain a bit of speed as it means they can run in parallel.

### CODE REVIEW

**Comment by nelsonkopliku** [comment]
The frontend test step is now a dead end, no one is depending on it. I am afraid we are missing something.
If everything suceceds, except for frontend tests, we'd be committing to OBS something potentially broken.

**Comment by dottorblaster** [comment]
I didn't propose a retry, I just said that splitting FE tests from BE tests (that is needed) doesn't prevent us from having to retry. The goal for me is having a CI that works, not a CI that automatically retries.

**Comment by rtorrero** [comment]
> I didn't propose a retry, I just said that splitting FE tests from BE tests (that is needed) doesn't prevent us from having to retry. The goal for me is having a CI that works, not a CI that automatically retries.

my bad, I re-read your message on slack and it makes more sense now :sweat_smile: . I'll drop the retry.

**Comment by nelsonkopliku** [comment]
I am afraid we still could be committing broken stuff to obs 

pipeline

**Comment by rtorrero** [comment]
> I am afraid we still could be committing broken stuff to obs
> 
> pipeline

I was just doing the push to address that (in fact I think I beat you :smile: for a few seconds)

**Review by nelsonkopliku — APPROVED** [review]
LGTM

**Review by dottorblaster — APPROVED** [review]
LGTM

**Pull request merged**
