### PR TITLE
Update outdated Agent message

### PR DESCRIPTION
**Pull request by stefanotorresi**
# Description

Updates a hard coded frontend warning message.

## Did you add the right label?

Trivial UX enhancement.

## How was this tested?

Automated JS frontend tests.

### CODE REVIEW

**Review by arbulu89 — COMMENTED** [review]
I let this @abravosuse @jagabomb

**Comment by abravosuse** [comment]
For me it is OK.

**Review by dottorblaster — APPROVED** [review]
LGTM, if the wording is validated we can merge :+1: 

(of course when the CI is green)

**Comment by arbulu89** [comment]
@stefanotorresi You need to update the test if you want this PR merged :see_no_evil:

**Pull request merged**
