### PR TITLE
Filter Component UI fixes

### PR DESCRIPTION
**Pull request by jagabomb**
# Description

Minor inconsistencies were happening with the Filter component. Here is a list of issues:

1. The last Filter component in a row was not aligned to the right hand-side of the Critical component. Also spacing between the component seemed to be too close.
2. The Clear icon was showing up in the default state of the filter and should only appear once the Filter has one or more values selected.

Screenshot 2023-03-03 at 09 29 19

### Below are screenshots of the fixes made:

**Default State**
Screenshot 2023-03-03 at 10 26 41

**Filter Value Set State**
Screenshot 2023-03-03 at 10 26 53

Lastly, a hover state (background colour of light gray) has also now been added to the Filter.
Screenshot 2023-03-03 at 10 30 58

## How was this tested?

Visually

### CODE REVIEW

**Review by EMaksy — APPROVED** [review]
Great Job,  your pr and trento web looks good to me.

**Review by arbulu89 — APPROVED** [review]
Looks good!

**Review by dottorblaster — APPROVED** [review]

**Comment by rtorrero** [comment]
@jagabomb great :-)! When I originally "fixed" this, it broke the alignment for the cluster settings buttons and header. I quickly deployed your PR to check it and it seems it's perfect now. Thanks!

**Review by rtorrero — APPROVED** [review]
LGTM

**Pull request merged**
