### PR TITLE
Add codespell job to the ci

### PR DESCRIPTION
**Pull request by arbulu89**
A small goodie to check spelling issues in the CI.
I thought of including it in `mix`, and it can be done. This was the easiest way. 
If you know how we could make this option more generally available, rather than only the CI, idea are welcomed

### CODE REVIEW

**Review by nelsonkopliku — COMMENTED** [review]
Interesting and funny because we can find new memes :joy: 

Might not be a crucial step in our CI, yet since it seems to not be that costly of a step and it improves a bit our lives, let's give it a try indeed!

I have only a doubt on the flow.

Here's how it was
image

And here's how it is 
image

Is this intentional to linearize what was parallel?

**Comment by arbulu89** [comment]
> Interesting and funny because we can find new memes joy
> 
> Might not be a crucial step in our CI, yet since it seems to not be that costly of a step and it improves a bit our lives, let's give it a try indeed!
> 
> I have only a doubt on the flow.
> 
> Here's how it was image
> 
> And here's how it is image
> 
> Is this intentional to linearize what was parallel?

@nelsonkopliku Yes, it was intentional, as I thought that we could maybe skip the E2E tests if the UT are failing.
Anyway, I will restore back to the original flow, and even run the tests even if the codespell fails, as they are not hard dependencies.

**Comment by nelsonkopliku** [comment]
> it was intentional, as I thought that we could maybe skip the E2E tests if the UT are failing. Anyway, I will restore back to the original flow, and even run the tests even if the codespell fails, as they are not hard dependencies.
> 
> **Edit**: Parallelized flow restored in: [f4b14f4](https://github.com/trento-project/web/commit/f4b14f4ad11b04f60d1d43066dbe364fb382e576)

I see.

I am now wondering whether it is a good thing to consider misspelling failures so critical to interrupt CI, even everything else is fine.

image

It's not a burden until it isn't :smile: and that clearly depends on how often we misspell _thigns_ :trollface:.
Hopefully we do not make that many mistakes to make this step a burden, and if it becomes we can decide to remove it or change strategy (for instance not breaking CI but just reporting misspells somehow and tackle them later).

I am fine with experimenting, let's not forget to consider value and costs :smile:

**Review by nelsonkopliku — APPROVED** [review]

**Comment by arbulu89** [comment]
@nelsonkopliku I will remove any deps from the codespell. So at least all the stages are executed, and as many of us have admin rights, we can merge even if this new stage fails

**Pull request merged**
