### PR TITLE
Api key Expiration Label fix

### PR DESCRIPTION
**Pull request by CDimonaco**
# Description

This pr fix the label shown in the Api key expiration toast.
There was a bug that even when the api key was expired, the toast had the label 'Api key expires in 0 days'.
The api key expiration checking and the security mechanism are not affected.

## How was this tested?

Automated tests

### CODE REVIEW

**Comment by abravosuse** [comment]
I have deployed the PR image in my testing environment and generated a key that expires in 3 days. That is next Monday. On Monday I will verify if the behavior is corrected.

BTW @CDimonaco did you also review the message in the Settings view? There is was saying "Key will expire 5 April 2024", but the key was already expired. It should have said that: "Key expired"

**Comment by CDimonaco** [comment]
> I have deployed the PR image in my testing environment and generated a key that expires in 3 days. That is next Monday. On Monday I will verify if the behavior is corrected.
> 
> BTW @CDimonaco did you also review the message in the Settings view? There it was saying "Key will expire 5 April 2024", but the key was already expired. It should have said that: "Key expired"

This is also fixed!

**Review by arbulu89 — APPROVED** [review]
If tested and working. All green from my side

**Review by abravosuse — APPROVED** [review]
All good to go @CDimonaco. All tested and working fine. Thanks!

**Pull request merged**
