### PR TITLE
Replace "SAP INSTANCES" title in Trento dashboard/home page

### PR DESCRIPTION
**Pull request by EMaksy**
# Description
Almost what the title says, just a replace of the title from "SAP INSTANCES" to "APPLICATION INSTANCES" .
### Before
Screenshot from 2023-10-18 13-16-00

### After
Screenshot from 2023-10-18 13-15-34

### CODE REVIEW

**Review by abravosuse — APPROVED** [review]
LGTM

**Comment by arbulu89** [comment]
> LGTM

@abravosuse @jagabomb Just we aware that this forces to header to have 2 lines instead of one. If we want to adjust a bit the styles

**Comment by abravosuse** [comment]
I think it depends on the width of the screen. Right now, if the screen is not wide enough, you also get a two-line headers, which is OK for me:
image

**Review by arbulu89 — APPROVED** [review]
If @abravosuse is happy, I'm happy

**Review by jagabomb — APPROVED** [review]
LGTM!

**Pull request merged**
