### PR TITLE
Add intermediate confirmation step in ApiKeySettingsModal

### PR DESCRIPTION
**Pull request by CDimonaco**
# Description

Add confirmation modal in ApiKeySettings dialog, to double check if the user wants to generate a new Api key

## How was this tested?

Automated/e2e tests

### CODE REVIEW

**Comment by jagabomb** [comment]
@CDimonaco Thanks for this. This works well for me and I see that it retains the state (values of) nicely. 😄  I would like you to add a full stop (**.**) at the end of the last sentence, _"This action cannot be undone_". I will double check the warning message in general with @abravosuse.

**Comment by jagabomb** [comment]
@CDimonaco Can we also change the warning message to say _" ...**on** all the registered hosts."_ instead of _" ...**in** all the registered hosts."_ So the full message is this... _"Generating a new API Key forces an update of the agent configuration on all the registered hosts. This action cannot be undone."_

**Review by jagabomb — APPROVED** [review]
LGTM

**Review by arbulu89 — APPROVED** [review]
Nice!
Loved the transition in storybook

**Review by EMaksy — APPROVED** [review]
Hey man great job lgtm!

**Pull request merged**
