### PR TITLE
Show password toggle on login

### PR DESCRIPTION
**Pull request by balanza**
# Description

Add toggle to show password on login

|Screenshot from 2024-12-06 11-44-39|Screenshot from 2024-12-06 11-45-18|
|-|-|

### CODE REVIEW

**Review by nelsonkopliku — COMMENTED** [review]
Nice idea!

Have you considered using the `Password` component we already have?

**Comment by stefanotorresi** [comment]
Great idea!

I know this will involve quite a lot of CSS wrestling but, for consistency, consider using the same UX we have for the SUMA settings password input, with a little eye icon embedded within the password input.

Screenshot 2024-12-06 115339

That said feel also free to first merge this and then follow up with the improved one at a later moment.

**Comment by stefanotorresi** [comment]
oh okay, from Nelson's comment I seem to understand that we can even reuse the same exact component, so one more reason to do it. 😄

**Review by nelsonkopliku — APPROVED** [review]
LGTM

**Comment by jagabomb** [comment]
@balanza Thanks for this! I think it really helps to create more consistency with the UX. I am willing to trade simple border colours for an overall better UX.

**Review by jagabomb — APPROVED** [review]
❤️ LGTM

**Pull request merged**
