### PR TITLE
Skip tests that are still missing bugfixes

### PR DESCRIPTION
**Pull request by rtorrero**
# Description

This PR adds .skips for tests that still require bugfixes to pass.

### CODE REVIEW

**Review by jamie-suse — APPROVED** [review]

**Review by arbulu89 — COMMENTED** [review]
@jamie-suse My PR would remove the 2nd skip.
Is your PR removing the other 2?

**Comment by jamie-suse** [comment]
> @jamie-suse My PR would remove the 2nd skip. Is your PR removing the other 2?

@arbulu89 @rtorrero Yeah, I can remove them in my PR :+1:

**Comment by arbulu89** [comment]
> > @jamie-suse My PR would remove the 2nd skip. Is your PR removing the other 2?
> 
> @arbulu89 @rtorrero Yeah, I can remove them in my PR +1

@jamie-suse but are both passing or the tests make sense?
I want to understand if we are making anything logic with this PR

**Comment by jamie-suse** [comment]
> @jamie-suse but are both passing or the tests make sense?
> I want to understand if we are making anything logic with this PR

Both tests are passing in my PR. They make sense to me as one is testing that the database restoration works, and the other is testing that when a SAP system is deregistered, the SID should be removed from Hosts (this test is in the Hosts List).

**Comment by arbulu89** [comment]
> > @jamie-suse but are both passing or the tests make sense?
> > I want to understand if we are making anything logic with this PR
> 
> Both tests are passing in my PR. They make sense to me as one is testing that the database restoration works, and the other is testing that when a SAP system is deregistered, the SID should be removed from Hosts (this test is in the Hosts List).

Okey them. Thank you for clarifying.

**Pull request merged**
