### PR TITLE
Updated logo assets

### PR DESCRIPTION
**Pull request by jagabomb**
# Description

This PR replaces old logo assets with the new logo

## How was this tested?

Not tested locally. (Unable to compile node assets on Mac currently).
It will be tested when Github builds the PR.

**Update**
Here are the screenshots from the PR Environment:
Screenshot 2024-01-30 at 10 41 06

Screenshot 2024-01-26 at 14 04 35

Screenshot 2024-01-26 at 14 06 59

### CODE REVIEW

**Review by nelsonkopliku — APPROVED** [review]
Looking good https://2229.prenv.trento.suse.com

**Comment by jagabomb** [comment]
@stefanotorresi Do you think for login, I could use a dark logo like this?
trento-icon-dark

**Review by dottorblaster — APPROVED** [review]
SHIP IT

**Comment by stefanotorresi** [comment]
> @stefanotorresi Do you think for login, I could use a dark logo like this?

I don't know, Jurgen, I'd have to see it to give you an opinion. It looks good as it is, anyway.

**Comment by jagabomb** [comment]
> > @stefanotorresi Do you think for login, I could use a dark logo like this?
> 
> I don't know, Jurgen, I'd have to see it to give you an opinion. It looks good as it is, anyway.

@stefanotorresi It would look like this...

**Comment by jagabomb** [comment]
> I like it the same! Go with whatever you like better. For the login page specifically, I liked the minimality of the light one, but the dark one looks very good as well.

@stefanotorresi Cool, I have added it because I like how it feels like an icon that opposed to just floating.

**Pull request merged**
