### PR TITLE
Add Authentication Documentation as ExDoc guide

### PR DESCRIPTION
**Pull request by CDimonaco**
# Description

As the title suggest

## How was this tested?

My eyes, heart and soul.

### CODE REVIEW

**Review by fabriziosestito — CHANGES_REQUESTED** [review]

**Review by nelsonkopliku — APPROVED** [review]
Cool!

**Comment by CDimonaco** [comment]
image

Refactored to have a dedicated section in the sidebar.

**Comment by CDimonaco** [comment]
Fixed comments

**Review by dottorblaster — APPROVED** [review]
LGTM

**Review by fabriziosestito — APPROVED** [review]

**Pull request merged**
