### PR TITLE
Remove debug code

### PR DESCRIPTION
**Pull request by nelsonkopliku**
As per the title

### CODE REVIEW

**Comment by dottorblaster** [comment]
Wait a minute... how did the CI pass? 0.o

**Comment by nelsonkopliku** [comment]
@dottorblaster no idea :trollface:

**Review by dottorblaster — APPROVED** [review]

**Comment by fabriziosestito** [comment]
@nelsonkopliku could we investigate why the CI is passing?

**Comment by nelsonkopliku** [comment]
The debug code was added in this PR https://github.com/trento-project/web/pull/1231, and then removed in the same PR (but I don't know precisely what has been done).
Eventually the PR https://github.com/trento-project/web/pull/1231 was merged and CI passed 'cause the debug code was not there.

However the commit adding that code (beef248c45689a6a5bc20127a41b38a47c59f71a) ended in `new-checks-ui` branch https://github.com/trento-project/web/commits/new-checks-ui outside of a PR (no idea how that happened) so it was never detected until I rebased this PR https://github.com/trento-project/web/pull/1232 on `new-checks-ui` branch getting a failure on code analysis.

**Pull request merged**
