### PR TITLE
Fix SMTP usage in runtime configuration

### PR DESCRIPTION
**Pull request by CDimonaco**
# Description

Fix SMTP usage in runtime

## How was this tested?

Manual testing

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
Great @CDimonaco 

As a matter of fact, we tried to use the [tls_certificate_check](https://hexdocs.pm/tls_certificate_check/readme.html) but you cannot use dependency function in the config files

**Review by nelsonkopliku — APPROVED** [review]
Good catch!

I was also debugging myself around that and noticed that what we currently provide as `ssl: :if_available` should actually be a boolean as mentioned here https://github.com/swoosh/swoosh/blob/v1.14.3/lib/swoosh/adapters/smtp.ex#L71

not sure whether we want to do something in that regard.

**Review by dottorblaster — APPROVED** [review]

**Review by EMaksy — APPROVED** [review]

**Comment by CDimonaco** [comment]
SSL Disabled in favour of TLS encryption. Thanks @nelsonkopliku  for spotting it

**Comment by gagandeepb** [comment]
One question to be addressed/explored, possibly at some later point, is that the Swoosh config provided is a deployment specific concern: IIUC there isn't a one single config that fits all cases (i.e. it depends on the config/settings of an external service, i.e. the SMTP server). Some servers may support STARTTLS and some may support TLS/SSL. I wonder if the observed bug, and consequently the fix here are too dependent on the SMTP server config? Note that Mailtrap, using which the bug was initially reported uses STARTTLS by default ([which requires setting ssl to false or omitting altogether, among other things](https://hexdocs.pm/swoosh/Swoosh.Adapters.SMTP.html#module-note)). I don't know what the server, against which this fix was validated, uses. I would be curious to hear your findings regarding this and/or pair on this (i.e. testing against SMTP server configs/ different OTP versions, etc.). Let me know if there is something that I have misunderstood about this.

**Comment by arbulu89** [comment]
@gagandeepb That's a fair concern.
We tested with `Mailtrap` and google SMTP server (`smtp.gmail.com`, port 587), I guess both `tls`, and that's why putting `ssl: false` helps in both cases.
Either way, we have a couple of options to improve this:
- Require usage of TLS based SMTP server to the user as SSL is deprecated
- Make the configuration available through env variables

**Pull request merged**
